config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :user_stocks, except:  [:show, :edit, :update]
  resources :users, only: [:show] 
  resources :friendships

  root 'welcome#index'
  get 'my_portfolio', to: "users#my_portfolio"
  get 'search_stocks', to: "stocks#search"
  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"
  

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :user_stocks
  has_many :users, through: :user_stocks
  # Class method to look up stock from Stock DB and return Stock object
  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
  
  # Class method to look up stock info from external source (GEM stock_quote)
  def self.new_from_lookup(ticker_symbol)
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    # if no stock found with given symbol return nil
    return nil unless looked_up_stock.name
    # If stock found then create and build stock object to be returned
    new_stock = new(ticker: looked_up_stock.symbol, name: looked_up_stock.name)
    new_stock.last_price = new_stock.price
    new_stock
  end
  
  # Price returned depends on whether market still open or already closed
  def price
    # if markets aren't closed there will not be a closing price yet.
    closing_price = StockQuote::Stock.quote(ticker).close
    return "#{closing_price} (Closing)" if closing_price
    
    # Opening price should be available but if not just return 'Unavailable'
    opening_price = StockQuote::Stock.quote(ticker).open
    return "#{opening_price} (Opening)" if opening_price
    
    'Unavailable'
  end
  
  
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    # debugger
    if params[:stock]
      @stock = Stock.find_by_ticker(params[:stock]) 
      @stock ||= Stock.new_from_lookup(params[:stock]) 
    end

    if @stock
      # By rendering json and entering app path/search_stocks?stock=GOOG
      # you will see jason object returned and confirm code is working
      # render json: @stock
      render partial:  'lookup'
    else
      render status: :not_found, nothing: true
    end
    
  end
  
end

app/views/stocks/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <% if @user.id == current_user.id %>
      <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user_stocks.each do |user_stock| %>
    <%# debugger %>
    <tr>
      <td><%= user_stock.stock.name %></td>
      <td><%= user_stock.stock.ticker %></td>
      <td><%= user_stock.stock.price %></td>
      <% if @user.id == current_user.id %>
      <td>
        <%= link_to 'Delete', user_stock_path(user_stock), 
                              :method => :delete,  
                              :data => { :confirm => "Are you sure?" },
                              :class => "btn btn-xs btn-danger" %>
      </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/stocks/_lookup.html.erb
<div id="stock-lookup">
  <h3>Search for Stocks</h3>
  <!-- Stock Search/Lookup Form-->
  <!-- Input will be submitted to server via AJAX as noted by 'remote: true' parameter-->
  <!-- An ID form is required so that we can refer to it in jquery/js code (stock.js) 
      where AJAX/JSON repsonse is handled -->
  <%= form_tag search_stocks_path, remote: true, method: :get, id: 'stock-lookup-form' do %>
  <div class="form-group row no-padding text-center col-md-12">
    <div class="col-md-10">
      <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true,
                                                          class: 'form-control search-box input-lg' %>
    </div>
    <div class="col-md-2">
      <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
        <i class="fa fa-search"></i> Look up a stock
      <% end %>
    </div>
  </div>
  <% end %>
  
  
  <!--Spinner symbol shown while waiting for stock lookups results to be returned -->
  <%= render 'common/spinner' %>
  
  <!-- Stock lookup results -->
  <% if @stock %>
    <div id="stock-lookup-results" class="well results-block">
      <strong>Symbol:&nbsp</strong><%= @stock.ticker %>&nbsp
      <strong>Name:&nbsp</strong><%= @stock.name %>&nbsp
      <strong>Price&nbsp</strong><%= @stock.price %>&nbsp
      <% if current_user.can_add_stock?(@stock.ticker) %>
      <!-- Create association -->
      <!--If the stock was already tracked it will have a stock_id otherwise you
          want to set to blank and then create new stock DB recored in the create action of UserStocks controller -->
        <!-- Note: that link specifies Post operation...this is needed because we are creating association in DB on server -->
        <%= link_to "Add to my Stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker, 
                                    stock_id: @stock_id ? @stock.id : ''), class: 'btn btn-xs btn-success', method: :post %>
      <% else %> <!-- can't add stock because of limit or already added --> 
        <span class="label label-default">
          Stock cannot be added because you have already added
          <% if !current_user.under_stock_limit? %>
            10 stocks
          <% end %>
          <% if current_user.stock_already_added?(@stock.ticker) %>
            this stock
          <% end %>
        </span>      
      <% end %>
    </div>
  <% end %>
  <div id="stock-lookup-errors"></div>
</div>